version: 1.0.{build}
image: Visual Studio 2015
environment:
  _TARGET_PLARFORM: 8.1
  _PLATFORM_TOOLSET: v140
platform:
  - x64
  - x86
configuration:
  - Debug
  - Release
artifacts:
  - path: $(configuration)\$(platform)\emit-x.exe
build:
  project: build.xml
  verbosity: normal
