version: 1.0.{build}
image: Visual Studio 2017
environment:
  TargetPlatformVersion: 8.1
  PlatformToolset: v141
  BuildVersion: $(appveyor_build_version)
platform:
  - x64
  - x86
configuration:
  - Debug
  - Release
artifacts:
  - path: $(configuration)\$(platform)\emit-x.exe
build:
  project: build.xml
  verbosity: normal
